### ISSUE TITLE
Issue with tensorflow

### ISSUE THREAD

**Issue by ndinarvand** [BertaBescos/DynaSLAM#46]
Hello everyone,
I follow steps to install DynaSLAM on my laptop but got following error:

navid@navid-X541UVK:~/DynaSLAM$ python src/python/Check.py
Traceback (most recent call last):
  File "src/python/Check.py", line 10, in <module>
    import coco
  File "/home/navid/DynaSLAM/src/python/coco.py", line 45, in <module>
    import utils
  File "/home/navid/DynaSLAM/src/python/utils.py", line 15, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow

Please help me.
Thanks alot.

**Comment by qamaruislam** [comment]
@ndinarvand I am also facing the same issue, Have you find the solution?
